server:
  port: 9083

spring:
  application:
    name: gateway-service
  profiles:
    active: dev

  cloud:
    nacos:
      server-addr: ${nacos.server-addr}
    gateway:
      routes:
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/content/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
